### ISSUE TITLE
Atualizar Scripts com comentários

### ISSUE THREAD

**Issue by EduardoPortoBaltazar** [gabrielbaltazar/TransferKids#8]
Ao final de cada tabela colocar o comentário dos atributos importantes.

**Comment by sauloand** [comment]
Inserir codigo Estado na tabela Endereço.
Inserir vencimento carteira na tabela Motorista.
Adicionar flgativo na tabela motorista.
Agendamento - usuário solicitação de cancelamento.

**Comment by sauloand** [comment]
Reunião 17/09/2016

**Comment by sauloand** [comment]
Reunião 17/09/2016
Criar a tabela EMPRESA no script do Diagrama de classe Client.

Criar script de inclusão do Diagrama de Classe do Admin.

Entrega para as 17/09/2016 as 20:00 hrs.

**Comment by sauloand** [comment]
Concluído a atividade base TransferKids e Native.
